### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hyandell** [TREMA-UNH/trec-car-tools-java#1]
Hi TREMA-UNH,

What's the license for trec-car-tools-java?

Is it BSD-3 clause like the Python code in trec-car-tools/python3?

**Comment by laura-dietz** [comment]
Hi Henri,
      
      Yes:  BSD 3-Clause
          
        thanks for pointing this out.  The license got
      lost in a refactoring spree.
      
          
          Best,
          Laura
          
        
      On 07/21/2018 02:50 AM, Henri Yandell wrote:
    
    
      
      Hi TREMA-UNH,
      What's the license for trec-car-tools-java?
      Is it BSD-3 clause like the Python code in
        trec-car-tools/python3?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TREMA-UNH/trec-car-tools-java","title":"TREMA-UNH/trec-car-tools-java","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/TREMA-UNH/trec-car-tools-java"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"License? (#1)"}],"action":{"name":"View Issue","url":"https://github.com/TREMA-UNH/trec-car-tools-java/issues/1"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools-java/issues/1",
"url": "https://github.com/TREMA-UNH/trec-car-tools-java/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "License? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Henri Yandell**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@hyandell",
"facts": [
{
"name": "Repository: ",
"value": "TREMA-UNH/trec-car-tools-java"
},
{
"name": "Issue #: ",
"value": 1
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"TREMA-UNH/trec-car-tools-java\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"TREMA-UNH/trec-car-tools-java\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/TREMA-UNH/trec-car-tools-java/issues/1"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 359011522\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by hyandell** [comment]
Thanks Laura - closing the issue :)
